# Generated by Django 4.0.3 on 2022-03-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETIQUETA', models.IntegerField()),
                ('RESPONSAVEL', models.CharField(max_length=150)),
                ('CPF_DO_RESPONSAVEL', models.CharField(max_length=30)),
                ('DESCRICAO_DO_EQUIPAMENTO', models.CharField(max_length=30)),
                ('MARCA', models.CharField(max_length=30)),
                ('MODELO', models.CharField(max_length=30)),
                ('NUMERO_DE_SERIE', models.CharField(max_length=30)),
                ('NUMERO_DA_NOTA_FISCAL', models.CharField(max_length=30)),
                ('LOCALIZACAO', models.CharField(max_length=30)),
                ('PROJETO', models.CharField(max_length=30)),
                ('ANO_DO_PROJETO', models.CharField(max_length=30)),
                ('EMPRESA_PATROCINADORA', models.CharField(max_length=30)),
            ],
        ),
    ]
